# Generated by Django 4.1.3 on 2022-12-04 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsusers',
            name='name',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
