# Generated by Django 4.1.3 on 2022-12-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsusers',
            options={'verbose_name': 'NewsUser', 'verbose_name_plural': 'NewsUsers'},
        ),
    ]
